### ISSUE TITLE
0.3.3 does not compile

### ISSUE THREAD

**Issue by 0-wiz-0** [gvansickle/ucg#122]
Please make a new release - 0.3.3 does not compile on my system (gcc 9.3.0 on NetBSD 9.99.81/amd64), while git head does.

The error in 0.3.3 is:
````
--- libext_la-DirTree.lo ---
In file included from DirTree.cpp:22:
DirTree.h:143:28: error: field 'm_file_basename_filter' has incomplete type 'DirTree::file_basename_filter_type' {aka 'std::function<bool(const std::__cxx11::basic_string<char>&) noexcept>'}
  143 |  file_basename_filter_type m_file_basename_filter;
      |                            ^~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/g++/functional:59,
                 from DirTree.h:27,
                 from DirTree.cpp:22:
/usr/include/g++/bits/std_function.h:128:11: note: declaration of 'using file_basename_filter_type = class std::function<bool(const std::__cxx11::basic_string<char>&) noexcept>' {aka 'class std::function<bool(const std::__cxx11::basic_string<char>&) noexcept>'}
  128 |     class function;
      |           ^~~~~~~~
In file included from DirTree.cpp:22:
DirTree.h:144:27: error: field 'm_dir_basename_filter' has incomplete type 'DirTree::dir_basename_filter_type' {aka 'std::function<bool(const std::__cxx11::basic_string<char>&) noexcept>'}
  144 |  dir_basename_filter_type m_dir_basename_filter;
      |                           ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/g++/functional:59,
                 from DirTree.h:27,
                 from DirTree.cpp:22:
/usr/include/g++/bits/std_function.h:128:11: note: declaration of 'using dir_basename_filter_type = class std::function<bool(const std::__cxx11::basic_string<char>&) noexcept>' {aka 'class std::function<bool(const std::__cxx11::basic_string<char>&) noexcept>'}
  128 |     class function;
      |           ^~~~~~~~
````

**Comment by bAndie91** [comment]
as i found out it is fixed in a38dac7a254093158d0808901d13b64e069d7d07
